name: Test Crypto Monitor

on:
  schedule:
    - cron: '*/10 * * * *'  # toutes les 10 minutes
  workflow_dispatch:        # permet aussi de lancer manuellement

jobs:
  test-monitor:
    runs-on: ubuntu-latest
    env:
      CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      FROM_PASS: ${{ secrets.FROM_PASS }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas flask

      - name: Run crypto monitor script
        run: |
          python Test.py
